### ISSUE TITLE
Problems creating new task.

### ISSUE THREAD

**Issue by RedTally** [aber-cs22120-group-15/TaskerMAN#26]
No test for date being submitted in a specific format, and nothing stopping dates being added, auto sets date for 0000-00-00, for "gbrbg4" or "201X-07-07". Years in the past can be added, e.g. "1999-07-07". 
Task can be added without a title, and without an initial step, and if initial step is added there is no way to add more steps than one without submitting the task and then adding them.
When task is created, the manage steps page is called "Mange Steps".
Edit: The sentence about the problem with adding dates only applies to Firefox. Google Chrome and Microsoft Edge have been tested and work. Dates in the past can still be added even on Chrome and Edge.

**Comment by RedTally** [comment]
Edit: The sentence about the problem with adding dates only applies to Firefox. Google Chrome and Microsoft Edge have been tested and work.

**Comment by dkmonaghan** [comment]
These should all be resolved now, can you test them @RedTally

**Comment by RedTally** [comment]
"Input due date is not valid" Error now always pops regardless of browser.

**Comment by dkmonaghan** [comment]
Should be resolved now. How does this behave in Firefox? @RedTally @lewrossi

**Comment by dkmonaghan** [comment]
Behaves correctly in Firefox as per testing by @lewrossi
