### ISSUE TITLE
Task Step Comment

### ISSUE THREAD

**Issue by RedTally** [aber-cs22120-group-15/TaskerMAN#28]
It is impossible to create a new task, because once all details are added, it error checks for details that cannot be added. If all details are added, the error message "Task Step comment cannot be blank" is thrown, but there is no space for a "Task Step Comment" available on the new task page. Task step comments can only be added once the task is created and being edited retroactively.

**Comment by dkmonaghan** [comment]
Try this again now. Should be fine. @RedTally
