### ISSUE TITLE
Task abandonment problem

### ISSUE THREAD

**Issue by RedTally** [aber-cs22120-group-15/TaskerMAN#30]
Tasks abandoned causing the number of pages on the view tasks tab to drop, do not delete the empty page.

E.g. If there are 3 pages and the third page has exactly 1 task on it, and any task is deleted, there will be three pages with 25/25/0 tasks per page, leaving page 3 as an empty page, instead of there being only 2 full pages.

**Comment by dkmonaghan** [comment]
This bug seems to have been caused due to test data which left some tasks with invalid data such as blank titles. A refresh of the data in the database has caused this bug to no longer appear to be an issue.

**Comment by RedTally** [comment]
There still seem to be problems with this. The version of the website I'm using now has an empty page 3 in the task list page.
